version: '3.1'

services:
  db:
    image: postgres:14
    #env_file: .env-dev
    restart: always
    #container_name: test_pg_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example_user
      POSTGRES_DB: example_db
    volumes:
      - db_data:/var/lib/postgresql/data
    #  - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro


  liquibase:
    image: liquibase/liquibase
    volumes:
      - ./liquibase/changelog/:/liquibase/changelog/
    depends_on:
      - db
    command:
      - --url=jdbc:postgresql://db:5432/example_db
      - --changeLogFile=/liquibase/changelog/changelog.xml
      - --username=example_user
      - --password=example
      - update

volumes:
  db_data:
