version: '3.1'

services:
  dbl:
    image: postgres:14
    #env_file: .env-dev
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: example_db
    volumes:
      - db_data_l:/var/lib/postgresql/data
      #- ./liquibase/changelog/init.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
    networks:
      - mynetwork

volumes:
  db_data_l:

networks:
  mynetwork:
